# Generated by Django 3.2 on 2021-06-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
